spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_warehouse?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.xzit.practice.tree.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true